linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - staticcheck
    - gocritic
    - gosimple
    - ineffassign
    - typecheck
    - unused
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - decorder
    - errname
    - errorlint
    - exhaustive
    - copyloopvar
    - forcetypeassert
    # - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - godot
    - goimports
    - mnd
    - lll
    - makezero
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - prealloc
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - unparam
    - whitespace
    - wsl
    # - wastedassign - запрещает делать short declare
    - gosec
    # - funlen
    # - gochecknoglobals
    # - depguard
    # - dupl
    # - exhaustruct

linters-settings:
  lll:
    tab-width: 1
    line-length: 140
  errcheck:
    check-type-assertions: true
    check-blank: true
  goconst:
    min-len: 2
    min-occurrences: 2
  nakedret:
    max-func-lines: 30
  nlreturn:
    block-size: 4
  govet:
    enable-all: false
    disable-all: false
  nolintlint:
    require-explanation: true
    require-specific: true
  wsl:
    allow-cuddle-declarations: true
    force-err-cuddling: true
    allow-assign-and-anything: true
  gocognit:
    min-complexity: 160

run:
  timeout: 5m
  concurrency: 4
