version: "3.9"

services:
  redis: 
    image: redis:7.4.2-alpine
    container_name: api_redis
    ports: 
      - "6379:6379"
    restart: always
    networks:
      - web-api
  
  postgresql:
    image: postgres:16-alpine
    container_name: api_postgresql
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=evernote
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - web-api

networks:
  web-api:
    driver: bridge