server:
  Port: 7000
  Mode: Development
  JwtSecretKey: evernote-jwt-secret-key
  ReadTimeout: 10s
  WriteTimeout: 10s
  CtxDefaultTimeout: 10s

logger:
  Development: true
  DisableCaller: false
  DisableStackTrace: false
  Encoding: json
  Level: info

postgres:
  host: localhost
  port: 5432
  user: postgres
  password: 123456
  db_name: evernote
  sslmode: disable

redis:
  address: localhost:6379
  password: ""

metrics:
  Url: 0.0.0.0:7070
  ServiceName: api

jaeger:
  Host: localhost:6831
  ServiceName: REST_API
  LogSpans: false
